export const evidence = [
  { id:"ev-001", title:"Guidance for planned peri-urban land transitions", type:"Policy", authority:"Department of Land Resources", year:2025, geography:"India", score:96, summary:"A policy framework for coordinating conversion controls, service planning and protection of high-value agricultural land around expanding cities.", tags:["peri-urban","land conversion","planning"], sourceUrl:"https://dolr.gov.in", checksum:"sha256:demo-001" },
  { id:"ev-002", title:"Groundwater stress and built-up expansion in the Chennai metropolitan fringe", type:"Research", authority:"National Institute of Urban Affairs", year:2024, geography:"Tamil Nadu", score:93, summary:"Spatial analysis identifies strong association between unplanned built-up growth, reduced recharge surfaces and local groundwater stress.", tags:["groundwater","urban growth","Chennai"], sourceUrl:"https://niua.in", checksum:"sha256:demo-002" },
  { id:"ev-003", title:"District groundwater assessment: Kancheepuram", type:"Dataset", authority:"Central Ground Water Board", year:2024, geography:"Kancheepuram", score:91, summary:"Block-level groundwater categorisation, extraction estimates and long-term water-level observations for district planning.", tags:["water stress","CGWB","district indicators"], sourceUrl:"https://cgwb.gov.in", checksum:"sha256:demo-003" },
  { id:"ev-004", title:"Tamil Nadu land-use and land-cover change atlas", type:"Dataset", authority:"NRSC / State Remote Sensing Centre", year:2023, geography:"Tamil Nadu", score:88, summary:"Comparable land-cover classes for assessing settlement growth, agriculture loss, surface water and ecological change.", tags:["remote sensing","land cover","GIS"], sourceUrl:"https://bhuvan.nrsc.gov.in", checksum:"sha256:demo-004" },
  { id:"ev-005", title:"Model provisions for transferable development rights", type:"Legal", authority:"Ministry of Housing and Urban Affairs", year:2022, geography:"India", score:84, summary:"Reference provisions and safeguards relevant to development rights, acquisition alternatives and urban growth management.", tags:["TDR","legal","urban policy"], sourceUrl:"https://mohua.gov.in", checksum:"sha256:demo-005" },
  { id:"ev-006", title:"Social safeguards in land pooling and readjustment", type:"Research", authority:"Indian Institute for Human Settlements", year:2024, geography:"Multiple states", score:82, summary:"Comparative evidence on consent, compensation, livelihood continuity and distribution of infrastructure benefits.", tags:["livelihood","equity","land pooling"], sourceUrl:"https://iihs.co.in", checksum:"sha256:demo-006" },
];

export const connectors = [
  { id:"ogd", name:"Open Government Data", owner:"data.gov.in", status:"live", purpose:"Public socioeconomic, programme and administrative datasets used for dashboard indicators.", endpoint:"/api/v1/adapters/ogd", refresh:"Daily catalogue sync" },
  { id:"research", name:"OpenAlex", owner:"OurResearch", status:"live", purpose:"Research discovery metadata, authorship, institutions and citation relationships.", endpoint:"/api/v1/adapters/openalex", refresh:"Weekly metadata sync" },
  { id:"bhuvan", name:"Bhuvan / NRSC", owner:"ISRO / NRSC", status:"sandbox", purpose:"Approved geospatial layers for land cover, water bodies and remote-sensing analysis.", endpoint:"/api/v1/adapters/bhuvan", refresh:"Dataset dependent" },
  { id:"dilrmp", name:"DILRMP / ULPIN", owner:"Department of Land Resources", status:"planned", purpose:"Parcel, survey, mutation and programme indicators subject to ministry authorisation.", endpoint:"/api/v1/adapters/dilrmp", refresh:"Requires data agreement" },
  { id:"tinai", name:"TiNAI", owner:"Government of Tamil Nadu", status:"planned", purpose:"State AI and analytical outputs exposed through an agreed interdepartmental contract.", endpoint:"/api/v1/adapters/tinai", refresh:"Requires state approval" },
  { id:"wris", name:"India-WRIS / CGWB", owner:"CWC / CGWB", status:"sandbox", purpose:"Water-resource and groundwater indicators for climate and land-use scenario assessment.", endpoint:"/api/v1/adapters/wris", refresh:"Monthly snapshot" },
] as const;
